# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ide-sandb-ms-ekscluster
  region: us-gov-west-1

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 3
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    ssh: # use existing EC2 key
      publicKeyName: ses-ide-sandb-bastion