# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "ses-ide-sandb-terraform-state-locks"
    encrypt        = true
    key            = "mgmt/terraform.tfstate"
    region         = "us-gov-west-1"
    bucket         = "ses-ide-sandb-terraform-state"
  }
}
